const recipe = (
  slug,
  title,
  prepMinutes,
  servings,
  mealTags,
  collectionTags,
  ingredients,
  steps,
  tip,
) => ({
  slug,
  title,
  prepMinutes,
  servings,
  mealTags,
  collectionTags,
  ingredients,
  steps,
  tip,
});

export const catalogRecipes = [
  recipe(
    "berry-overnight-oats",
    "Berry Overnight Oats",
    10,
    2,
    ["breakfast"],
    ["make-ahead", "vegetarian"],
    [
      "1 cup rolled oats",
      "1 cup milk",
      "½ cup Greek yogurt",
      "1 tbsp chia seeds",
      "1 tbsp maple syrup",
      "1 cup mixed berries",
    ],
    [
      "Stir the oats, milk, yogurt, chia seeds, and maple syrup together in a lidded container.",
      "Fold in half the berries, cover, and refrigerate for at least 6 hours.",
      "Stir, loosen with a splash of milk if needed, and top with the remaining berries.",
    ],
    "Keeps refrigerated for up to 3 days.",
  ),
  recipe(
    "shakshuka",
    "Weekday Shakshuka",
    30,
    4,
    ["breakfast", "lunch"],
    ["middle-eastern", "vegetarian"],
    [
      "1 tbsp olive oil",
      "1 onion, diced",
      "1 red pepper, diced",
      "2 garlic cloves, minced",
      "1 tsp ground cumin",
      "½ tsp smoked paprika",
      "800 g chopped tomatoes",
      "4 eggs",
      "40 g feta",
      "2 tbsp chopped parsley",
    ],
    [
      "Soften the onion and pepper in olive oil over medium heat for 8 minutes.",
      "Add garlic and spices; cook for 1 minute, then add tomatoes and simmer until thick, about 10 minutes.",
      "Make four wells, crack in the eggs, cover, and cook for 5–7 minutes until the whites set.",
      "Scatter with feta and parsley before serving.",
    ],
    "Keep the yolks soft by taking the pan off the heat as soon as the whites are opaque.",
  ),
  recipe(
    "banana-oat-pancakes",
    "Banana Oat Pancakes",
    20,
    2,
    ["breakfast"],
    ["quick", "vegetarian"],
    [
      "1 ripe banana",
      "2 eggs",
      "¾ cup rolled oats",
      "½ tsp baking powder",
      "½ tsp cinnamon",
      "Pinch of salt",
      "1 tsp butter",
      "Berries, to serve",
    ],
    [
      "Blend the banana, eggs, oats, baking powder, cinnamon, and salt until mostly smooth.",
      "Rest the batter for 5 minutes while a non-stick pan warms over medium-low heat.",
      "Melt a little butter and cook small pancakes for 2 minutes per side.",
      "Serve warm with berries.",
    ],
    "Small pancakes are easier to turn because this batter is tender.",
  ),
  recipe(
    "spinach-feta-omelette",
    "Spinach and Feta Omelette",
    15,
    1,
    ["breakfast", "lunch"],
    ["quick", "vegetarian"],
    [
      "3 eggs",
      "1 tbsp milk",
      "1 tsp olive oil",
      "1 packed cup baby spinach",
      "40 g feta, crumbled",
      "6 cherry tomatoes, halved",
      "Salt and black pepper",
    ],
    [
      "Whisk the eggs with milk, salt, and pepper.",
      "Wilt the spinach in olive oil, then transfer it to a plate.",
      "Pour the eggs into the pan and cook gently, drawing the set edges inward.",
      "Add spinach and feta to one half, fold, and serve with the tomatoes.",
    ],
    "Low heat keeps the omelette tender.",
  ),
  recipe(
    "yogurt-granola-bowl",
    "Yogurt, Peach and Granola Bowl",
    5,
    1,
    ["breakfast", "snack"],
    ["no-cook", "vegetarian"],
    [
      "200 g Greek yogurt",
      "1 ripe peach, sliced",
      "⅓ cup granola",
      "¼ cup mixed berries",
      "1 tsp honey",
      "1 tbsp pumpkin seeds",
    ],
    [
      "Spoon the yogurt into a bowl.",
      "Arrange the peach, granola, berries, and pumpkin seeds on top.",
      "Drizzle with honey just before eating.",
    ],
    "Add granola at the last moment so it stays crisp.",
  ),
  recipe(
    "breakfast-burrito",
    "Black Bean Breakfast Burrito",
    25,
    2,
    ["breakfast", "lunch"],
    ["mexican-inspired", "high-protein"],
    [
      "4 eggs",
      "2 large flour tortillas",
      "½ cup black beans, drained",
      "½ red pepper, diced",
      "½ avocado, diced",
      "60 g cheddar, grated",
      "2 tbsp salsa",
      "1 tsp olive oil",
    ],
    [
      "Cook the pepper in olive oil for 4 minutes, then add the beans to warm through.",
      "Scramble the eggs gently in the same pan.",
      "Divide eggs, beans, pepper, avocado, cheese, and salsa between the tortillas.",
      "Fold tightly and toast seam-side down for 2 minutes per side.",
    ],
    "Wrap cooled burritos and freeze for an easy breakfast.",
  ),
  recipe(
    "apple-cinnamon-porridge",
    "Apple Cinnamon Porridge",
    15,
    2,
    ["breakfast"],
    ["budget", "vegetarian"],
    [
      "1 cup rolled oats",
      "2 cups milk",
      "1 apple, cored and sliced",
      "1 tsp butter",
      "½ tsp cinnamon",
      "1 tbsp maple syrup",
      "2 tbsp walnuts",
    ],
    [
      "Simmer the oats and milk with a pinch of salt for 6–8 minutes, stirring often.",
      "Meanwhile, cook the apple in butter and cinnamon until tender and golden.",
      "Divide the porridge between bowls and top with apple, maple syrup, and walnuts.",
    ],
    "Use half milk and half water for a lighter bowl.",
  ),

  recipe(
    "lemon-chickpea-salad",
    "Lemon Chickpea Salad",
    15,
    4,
    ["lunch"],
    ["mediterranean", "vegetarian", "no-cook"],
    [
      "2 x 400 g cans chickpeas, drained",
      "1 cucumber, chopped",
      "250 g cherry tomatoes, halved",
      "¼ red onion, thinly sliced",
      "100 g feta",
      "½ cup parsley",
      "1 lemon",
      "3 tbsp olive oil",
    ],
    [
      "Whisk the lemon juice and olive oil with salt and pepper.",
      "Combine chickpeas, cucumber, tomatoes, onion, and parsley.",
      "Toss with the dressing and crumble feta over the top.",
    ],
    "Rinse the sliced onion in cold water for a milder flavour.",
  ),
  recipe(
    "roasted-tomato-soup",
    "Roasted Tomato Basil Soup",
    45,
    4,
    ["lunch", "dinner"],
    ["comfort-food", "vegetarian"],
    [
      "1.2 kg ripe tomatoes, halved",
      "1 onion, cut into wedges",
      "4 garlic cloves",
      "2 tbsp olive oil",
      "500 ml vegetable stock",
      "½ cup basil leaves",
      "2 tbsp cream, optional",
    ],
    [
      "Heat the oven to 220°C. Roast tomatoes, onion, and garlic with olive oil, salt, and pepper for 30 minutes.",
      "Transfer to a saucepan, add stock, and simmer for 5 minutes.",
      "Add basil and blend until smooth.",
      "Taste for seasoning and finish with cream if using.",
    ],
    "A pinch of sugar balances tomatoes that are especially tart.",
  ),
  recipe(
    "sesame-soba-bowl",
    "Sesame Soba Noodle Bowl",
    25,
    4,
    ["lunch", "dinner"],
    ["asian-inspired", "vegan", "quick"],
    [
      "250 g soba noodles",
      "1 cup shelled edamame",
      "1 cucumber",
      "2 carrots, shredded",
      "3 spring onions",
      "2 tbsp soy sauce",
      "1½ tbsp rice vinegar",
      "1 tbsp sesame oil",
      "1 tsp grated ginger",
      "1 tbsp sesame seeds",
    ],
    [
      "Cook the soba according to the packet, adding edamame for the final 2 minutes; rinse cold and drain well.",
      "Whisk soy sauce, vinegar, sesame oil, and ginger.",
      "Toss noodles and edamame with cucumber, carrot, spring onion, and dressing.",
      "Finish with sesame seeds.",
    ],
    "Rinsing soba removes excess starch and prevents clumping.",
  ),
  recipe(
    "turkey-avocado-wrap",
    "Turkey Avocado Wrap",
    10,
    2,
    ["lunch"],
    ["quick", "high-protein"],
    [
      "2 wholegrain wraps",
      "160 g sliced roast turkey",
      "1 avocado, sliced",
      "1 tomato, sliced",
      "2 cups mixed leaves",
      "2 tbsp Greek yogurt",
      "1 tsp Dijon mustard",
      "1 tsp lemon juice",
    ],
    [
      "Mix yogurt, mustard, and lemon juice; season with pepper.",
      "Spread the sauce over each wrap.",
      "Layer with leaves, turkey, tomato, and avocado.",
      "Fold in the sides, roll tightly, and halve.",
    ],
    "Pat the tomato dry to keep a packed wrap from becoming soggy.",
  ),
  recipe(
    "coconut-lentil-soup",
    "Coconut Red Lentil Soup",
    35,
    4,
    ["lunch", "dinner"],
    ["vegan", "one-pot"],
    [
      "1 tbsp olive oil",
      "1 onion, diced",
      "2 carrots, diced",
      "2 garlic cloves, minced",
      "1 tbsp grated ginger",
      "1 tsp turmeric",
      "1 tsp ground cumin",
      "1 cup red lentils",
      "400 ml coconut milk",
      "750 ml vegetable stock",
      "1 lime",
    ],
    [
      "Soften onion and carrot in olive oil for 7 minutes.",
      "Add garlic, ginger, turmeric, and cumin; stir for 1 minute.",
      "Add lentils, coconut milk, and stock; simmer for 20 minutes until tender.",
      "Season and finish with lime juice.",
    ],
    "The soup thickens as it stands; loosen leftovers with water.",
  ),
  recipe(
    "mediterranean-quinoa-bowl",
    "Mediterranean Quinoa Bowl",
    35,
    4,
    ["lunch", "dinner"],
    ["mediterranean", "vegetarian"],
    [
      "1 cup quinoa",
      "1 courgette, sliced",
      "1 red pepper, sliced",
      "1 x 400 g can chickpeas",
      "1 cucumber, chopped",
      "½ cup olives",
      "100 g feta",
      "1 lemon",
      "2 tbsp olive oil",
    ],
    [
      "Cook the quinoa according to the packet and leave it to steam dry.",
      "Roast courgette, pepper, and chickpeas at 220°C with 1 tbsp oil for 20 minutes.",
      "Whisk remaining oil with lemon juice, salt, and pepper.",
      "Build bowls with quinoa, roasted vegetables, cucumber, olives, feta, and dressing.",
    ],
    "Cool every component before packing for lunch.",
  ),
  recipe(
    "tuna-white-bean-salad",
    "Tuna and White Bean Salad",
    15,
    3,
    ["lunch"],
    ["mediterranean", "no-cook", "high-protein"],
    [
      "2 x 160 g cans tuna, drained",
      "1 x 400 g can cannellini beans, drained",
      "200 g cherry tomatoes",
      "½ small red onion, sliced",
      "2 cups rocket",
      "2 tbsp parsley",
      "1 lemon",
      "2 tbsp olive oil",
    ],
    [
      "Whisk lemon juice and olive oil with salt and black pepper.",
      "Combine beans, tomatoes, onion, rocket, and parsley.",
      "Fold through the tuna gently, then dress and serve.",
    ],
    "Oil-packed tuna gives the richest result; drain it well first.",
  ),
  recipe(
    "roasted-vegetable-couscous",
    "Roasted Vegetable Couscous",
    35,
    4,
    ["lunch", "dinner"],
    ["mediterranean", "vegan"],
    [
      "1 aubergine, cubed",
      "1 courgette, sliced",
      "1 red pepper, sliced",
      "1 x 400 g can chickpeas",
      "2 tbsp olive oil",
      "1½ cups couscous",
      "1½ cups vegetable stock",
      "½ cup mint",
      "¼ cup toasted almonds",
      "1 lemon",
    ],
    [
      "Roast aubergine, courgette, pepper, and chickpeas with oil at 220°C for 25 minutes.",
      "Pour hot stock over couscous, cover for 5 minutes, then fluff with a fork.",
      "Fold in the roasted vegetables, mint, almonds, lemon zest, and juice.",
    ],
    "Season the vegetables before roasting so the couscous needs less adjustment.",
  ),

  recipe(
    "hummus-crunchy-vegetables",
    "Hummus with Crunchy Vegetables",
    10,
    4,
    ["snack"],
    ["vegan", "no-cook"],
    [
      "1 x 400 g can chickpeas, drained",
      "3 tbsp tahini",
      "1 lemon",
      "1 garlic clove",
      "2 tbsp olive oil",
      "½ tsp ground cumin",
      "1 cucumber",
      "2 carrots",
      "2 bell peppers",
    ],
    [
      "Blend chickpeas, tahini, lemon juice, garlic, cumin, and 3 tbsp cold water until smooth.",
      "Blend in olive oil and season to taste.",
      "Cut the vegetables into batons and serve alongside the hummus.",
    ],
    "An ice cube blended into the hummus makes it especially light.",
  ),
  recipe(
    "peanut-oat-energy-bites",
    "Peanut Oat Energy Bites",
    15,
    12,
    ["snack"],
    ["make-ahead", "no-cook", "vegetarian"],
    [
      "1 cup rolled oats",
      "½ cup peanut butter",
      "⅓ cup soft dates, chopped",
      "2 tbsp ground flaxseed",
      "2 tbsp honey",
      "¼ cup dark chocolate, finely chopped",
      "Pinch of salt",
    ],
    [
      "Mix all ingredients thoroughly in a bowl.",
      "Chill for 20 minutes if the mixture feels sticky.",
      "Roll into 12 balls and refrigerate in a sealed container.",
    ],
    "Lightly damp hands make rolling easier.",
  ),
  recipe(
    "baked-apple-yogurt",
    "Cinnamon Apple with Yogurt",
    15,
    2,
    ["snack", "breakfast"],
    ["quick", "vegetarian"],
    [
      "2 apples, cored and sliced",
      "1 tsp butter",
      "½ tsp cinnamon",
      "1 tsp maple syrup",
      "250 g Greek yogurt",
      "2 tbsp walnuts, chopped",
    ],
    [
      "Cook apples, butter, cinnamon, and 2 tbsp water in a covered pan for 6 minutes.",
      "Remove the lid and cook until the apples are golden and the liquid has reduced.",
      "Serve warm with yogurt, maple syrup, and walnuts.",
    ],
    "Choose a firm apple so the slices hold their shape.",
  ),
  recipe(
    "caprese-skewers",
    "Caprese Skewers",
    15,
    6,
    ["snack"],
    ["italian", "no-cook", "vegetarian"],
    [
      "250 g cherry tomatoes",
      "250 g mini mozzarella balls",
      "1 bunch basil",
      "1 tbsp extra-virgin olive oil",
      "1 tbsp balsamic glaze",
      "Black pepper",
    ],
    [
      "Thread a tomato, folded basil leaf, and mozzarella ball onto each small skewer.",
      "Arrange on a plate and drizzle with olive oil and balsamic glaze.",
      "Finish with black pepper and serve promptly.",
    ],
    "Drain and pat the mozzarella dry so the platter stays neat.",
  ),
  recipe(
    "crispy-spiced-chickpeas",
    "Crispy Spiced Chickpeas",
    35,
    4,
    ["snack"],
    ["vegan", "budget"],
    [
      "2 x 400 g cans chickpeas, drained",
      "1½ tbsp olive oil",
      "1 tsp smoked paprika",
      "½ tsp ground cumin",
      "½ tsp garlic powder",
      "½ tsp salt",
    ],
    [
      "Heat the oven to 210°C and dry the chickpeas very thoroughly.",
      "Toss with oil and salt, then roast for 25–30 minutes, shaking twice.",
      "Toss the hot chickpeas with paprika, cumin, and garlic powder; cool before eating.",
    ],
    "They crisp further as they cool, so leave them uncovered.",
  ),

  recipe(
    "sheet-pan-lemon-chicken",
    "Sheet-Pan Lemon Herb Chicken",
    50,
    4,
    ["dinner"],
    ["one-pan", "high-protein"],
    [
      "8 bone-in chicken thighs",
      "700 g baby potatoes, halved",
      "300 g green beans",
      "2 lemons",
      "3 garlic cloves, minced",
      "2 tbsp olive oil",
      "1 tbsp chopped rosemary",
    ],
    [
      "Heat the oven to 220°C. Toss potatoes with half the oil and roast for 15 minutes.",
      "Rub chicken with remaining oil, garlic, rosemary, lemon zest, salt, and pepper.",
      "Add chicken and lemon halves to the tray; roast for 25 minutes.",
      "Add green beans and roast for 10 more minutes, until the chicken reaches 75°C.",
    ],
    "Give the potatoes a head start so everything finishes together.",
  ),
  recipe(
    "mushroom-risotto",
    "Creamy Mushroom Risotto",
    45,
    4,
    ["dinner"],
    ["italian", "vegetarian"],
    [
      "300 g mixed mushrooms, sliced",
      "1 tbsp olive oil",
      "25 g butter",
      "1 onion, finely diced",
      "2 garlic cloves",
      "300 g arborio rice",
      "150 ml dry white wine",
      "1 litre hot vegetable stock",
      "60 g parmesan",
      "2 tbsp parsley",
    ],
    [
      "Brown mushrooms in olive oil over high heat; season and set aside.",
      "Soften onion in half the butter, add garlic and rice, and stir for 2 minutes.",
      "Add wine and let it absorb, then add hot stock a ladle at a time, stirring until the rice is tender.",
      "Fold in mushrooms, remaining butter, parmesan, and parsley; rest for 2 minutes.",
    ],
    "The finished risotto should spread slowly when spooned onto a plate.",
  ),
  recipe(
    "ginger-sesame-tofu",
    "Ginger Sesame Tofu Stir-Fry",
    30,
    4,
    ["dinner", "lunch"],
    ["asian-inspired", "vegan", "quick"],
    [
      "450 g firm tofu, pressed and cubed",
      "1 tbsp cornflour",
      "2 tbsp neutral oil",
      "1 head broccoli, cut into florets",
      "1 red pepper, sliced",
      "150 g sugar snap peas",
      "2 tbsp soy sauce",
      "1 tbsp rice vinegar",
      "1 tsp sesame oil",
      "1 tbsp grated ginger",
      "2 garlic cloves",
    ],
    [
      "Coat tofu with cornflour and a pinch of salt.",
      "Brown tofu in half the oil until crisp, then set aside.",
      "Stir-fry the vegetables in remaining oil for 5 minutes.",
      "Add soy sauce, vinegar, sesame oil, ginger, garlic, and tofu; toss for 2 minutes.",
    ],
    "Pressing tofu for 15 minutes gives it a much crisper crust.",
  ),
  recipe(
    "mustard-herb-salmon",
    "Mustard Herb Salmon with Crushed Potatoes",
    40,
    4,
    ["dinner"],
    ["high-protein", "one-pan"],
    [
      "4 salmon fillets",
      "700 g baby potatoes",
      "300 g asparagus",
      "1 tbsp wholegrain mustard",
      "1 tbsp Dijon mustard",
      "1 lemon",
      "2 tbsp olive oil",
      "2 tbsp chopped dill",
    ],
    [
      "Boil potatoes for 15 minutes, drain, and lightly crush on a baking tray.",
      "Drizzle with half the oil and roast at 220°C for 15 minutes.",
      "Mix mustards, lemon zest, and dill; spread over salmon.",
      "Add salmon and asparagus with remaining oil and roast for 10–12 minutes.",
    ],
    "Take salmon out when its centre still looks slightly translucent.",
  ),
  recipe(
    "red-lentil-dal",
    "Everyday Red Lentil Dal",
    40,
    4,
    ["dinner", "lunch"],
    ["indian-inspired", "vegan", "budget"],
    [
      "1½ cups red lentils",
      "1 tbsp neutral oil",
      "1 onion, diced",
      "3 garlic cloves",
      "1 tbsp grated ginger",
      "2 tsp ground cumin",
      "1 tsp turmeric",
      "1 tsp garam masala",
      "400 g chopped tomatoes",
      "800 ml vegetable stock",
      "1 lime",
      "Coriander, to serve",
    ],
    [
      "Rinse lentils until the water runs mostly clear.",
      "Soften onion in oil, then add garlic, ginger, and spices for 1 minute.",
      "Add tomatoes, lentils, and stock; simmer gently for 25 minutes, stirring occasionally.",
      "Season with salt and lime juice and finish with coriander.",
    ],
    "Add a splash of water whenever the lentils begin to catch.",
  ),
  recipe(
    "weeknight-beef-tacos",
    "Weeknight Beef Tacos",
    30,
    4,
    ["dinner"],
    ["mexican-inspired", "family"],
    [
      "500 g lean minced beef",
      "1 onion, diced",
      "2 garlic cloves",
      "2 tsp ground cumin",
      "1 tsp smoked paprika",
      "1 tbsp tomato paste",
      "12 small corn tortillas",
      "2 cups shredded cabbage",
      "1 avocado",
      "1 cup tomato salsa",
      "2 limes",
    ],
    [
      "Brown beef and onion in a hot pan for 8 minutes, breaking up the meat.",
      "Add garlic, spices, tomato paste, 100 ml water, and salt; simmer until glossy.",
      "Warm the tortillas in a dry pan.",
      "Fill with beef, cabbage, avocado, salsa, and lime.",
    ],
    "Set the toppings out separately so everyone can build their own.",
  ),
  recipe(
    "pesto-pasta",
    "Pesto Pasta with Peas and Courgette",
    25,
    4,
    ["dinner", "lunch"],
    ["italian", "quick", "vegetarian"],
    [
      "350 g short pasta",
      "2 courgettes, ribboned",
      "1 cup frozen peas",
      "½ cup basil pesto",
      "50 g parmesan",
      "¼ cup toasted pine nuts",
      "1 lemon",
    ],
    [
      "Cook pasta in salted water; add peas for the final 2 minutes and reserve a mug of cooking water.",
      "Sauté courgette ribbons in a wide pan for 3 minutes.",
      "Add drained pasta and peas, pesto, lemon juice, and enough cooking water to make a silky sauce.",
      "Finish with parmesan and pine nuts.",
    ],
    "Let the pan cool briefly before adding pesto to keep its basil flavour bright.",
  ),
  recipe(
    "turkey-meatballs",
    "Herbed Turkey Meatballs",
    45,
    4,
    ["dinner"],
    ["family", "high-protein"],
    [
      "500 g turkey mince",
      "½ cup fresh breadcrumbs",
      "1 egg",
      "2 garlic cloves, minced",
      "½ cup parsley, chopped",
      "40 g parmesan",
      "1 tbsp olive oil",
      "700 ml tomato passata",
      "½ tsp dried oregano",
    ],
    [
      "Mix turkey, breadcrumbs, egg, half the garlic, half the parsley, parmesan, salt, and pepper; shape into 16 balls.",
      "Brown the meatballs in olive oil, turning carefully.",
      "Add remaining garlic, passata, and oregano; cover and simmer for 20 minutes.",
      "Check the centres reach 74°C and finish with parsley.",
    ],
    "Wet hands lightly before shaping to prevent sticking.",
  ),
  recipe(
    "coconut-fish-curry",
    "Coconut Fish Curry",
    35,
    4,
    ["dinner"],
    ["asian-inspired", "one-pot"],
    [
      "600 g firm white fish, cut into chunks",
      "1 tbsp neutral oil",
      "1 onion, sliced",
      "2 garlic cloves",
      "1 tbsp grated ginger",
      "2 tbsp mild curry paste",
      "400 ml coconut milk",
      "1 red pepper, sliced",
      "150 g baby spinach",
      "1 lime",
      "Coriander, to serve",
    ],
    [
      "Soften onion in oil for 6 minutes; add garlic, ginger, and curry paste for 1 minute.",
      "Add coconut milk and pepper and simmer for 8 minutes.",
      "Nestle in the fish, cover, and simmer gently for 6–8 minutes until opaque.",
      "Fold in spinach, season with lime juice, and finish with coriander.",
    ],
    "Stir gently after adding the fish so the chunks remain whole.",
  ),
  recipe(
    "aubergine-parmesan",
    "Aubergine Parmesan",
    70,
    6,
    ["dinner"],
    ["italian", "vegetarian", "comfort-food"],
    [
      "3 aubergines, sliced lengthways",
      "3 tbsp olive oil",
      "2 garlic cloves",
      "800 g chopped tomatoes",
      "1 tsp dried oregano",
      "1 cup basil leaves",
      "250 g mozzarella, torn",
      "80 g parmesan, grated",
    ],
    [
      "Heat the oven to 220°C. Brush aubergine with 2 tbsp oil, season, and roast for 25 minutes.",
      "Cook garlic in remaining oil, add tomatoes and oregano, and simmer for 15 minutes.",
      "Layer tomato sauce, aubergine, basil, mozzarella, and parmesan in a baking dish.",
      "Bake for 25 minutes until bubbling; rest for 10 minutes before serving.",
    ],
    "Resting lets the layers settle and makes serving much cleaner.",
  ),
  recipe(
    "savoury-mushroom-toast",
    "Savoury Mushroom Toast",
    20,
    2,
    ["breakfast", "lunch"],
    ["quick", "vegetarian"],
    [
      "250 g chestnut mushrooms, sliced",
      "1 tbsp olive oil",
      "1 garlic clove, minced",
      "1 tsp thyme leaves",
      "2 thick slices sourdough",
      "2 eggs",
      "Salt and black pepper",
    ],
    [
      "Cook the mushrooms in olive oil over medium-high heat for 6–8 minutes until deeply browned.",
      "Add garlic and thyme and cook for 1 minute; season well.",
      "Toast the sourdough and poach or fry the eggs to your liking.",
      "Pile the mushrooms onto the toast and top each slice with an egg.",
    ],
    "Give the mushrooms room in the pan so they brown instead of steaming.",
  ),
  recipe(
    "mango-coconut-chia-pudding",
    "Mango Coconut Chia Pudding",
    10,
    2,
    ["breakfast", "snack"],
    ["make-ahead", "vegan", "tropical"],
    [
      "⅓ cup chia seeds",
      "1 cup light coconut milk",
      "1 tsp maple syrup",
      "1 ripe mango",
      "2 tbsp toasted coconut flakes",
      "Pinch of salt",
    ],
    [
      "Whisk the chia seeds, coconut milk, maple syrup, and salt together.",
      "Rest for 10 minutes, whisk again, then cover and chill for at least 4 hours.",
      "Blend half the mango and dice the rest.",
      "Layer the pudding with mango purée and finish with diced mango and coconut.",
    ],
    "Whisking twice prevents the chia seeds from settling in clumps.",
  ),
  recipe(
    "breakfast-fried-rice",
    "Breakfast Fried Rice",
    20,
    2,
    ["breakfast", "lunch"],
    ["quick", "asian-inspired"],
    [
      "2 cups cold cooked rice",
      "3 eggs",
      "1 carrot, finely diced",
      "½ cup frozen peas",
      "3 spring onions, sliced",
      "1 tbsp neutral oil",
      "1½ tbsp soy sauce",
      "1 tsp toasted sesame oil",
    ],
    [
      "Scramble the eggs in half the neutral oil, then transfer to a plate.",
      "Cook the carrot and peas in the remaining oil for 3 minutes.",
      "Add cold rice and fry over high heat until hot and lightly crisp.",
      "Fold in the eggs, spring onion, soy sauce, and sesame oil.",
    ],
    "Day-old chilled rice gives the best separate grains.",
  ),
  recipe(
    "baked-eggs-spinach-tomatoes",
    "Baked Eggs with Spinach and Tomatoes",
    25,
    2,
    ["breakfast", "lunch"],
    ["vegetarian", "one-pan"],
    [
      "1 tbsp olive oil",
      "200 g cherry tomatoes",
      "120 g baby spinach",
      "4 eggs",
      "50 g feta, crumbled",
      "½ tsp dried oregano",
      "Salt and black pepper",
    ],
    [
      "Heat the oven to 200°C.",
      "Cook the tomatoes in an ovenproof pan with olive oil and oregano for 5 minutes, then wilt in the spinach.",
      "Make four wells and crack in the eggs; scatter over the feta.",
      "Bake for 8–11 minutes until the whites are set and yolks remain soft.",
    ],
    "Take the pan out while the yolks still wobble slightly; they continue to cook.",
  ),
  recipe(
    "pear-almond-baked-oats",
    "Pear Almond Baked Oats",
    40,
    4,
    ["breakfast"],
    ["make-ahead", "vegetarian"],
    [
      "2 cups rolled oats",
      "1 tsp baking powder",
      "1 tsp cinnamon",
      "2 ripe pears, sliced",
      "2 cups milk",
      "1 egg",
      "2 tbsp maple syrup",
      "½ tsp almond extract",
      "¼ cup flaked almonds",
    ],
    [
      "Heat the oven to 190°C and lightly grease a baking dish.",
      "Mix the oats, baking powder, and cinnamon; arrange the pears through the mixture.",
      "Whisk milk, egg, maple syrup, and almond extract and pour evenly over the oats.",
      "Top with almonds and bake for 28–32 minutes until set and golden.",
    ],
    "Reheat portions with a splash of milk to restore their soft texture.",
  ),
  recipe(
    "smoked-salmon-rye-toasts",
    "Smoked Salmon Rye Toasts",
    10,
    2,
    ["breakfast", "lunch"],
    ["no-cook", "scandinavian-inspired"],
    [
      "4 slices rye bread",
      "120 g cream cheese",
      "150 g smoked salmon",
      "½ cucumber, ribboned",
      "1 tbsp capers",
      "2 tbsp fresh dill",
      "½ lemon",
      "Black pepper",
    ],
    [
      "Toast the rye bread until crisp at the edges.",
      "Spread each slice with cream cheese.",
      "Layer with smoked salmon and cucumber ribbons.",
      "Finish with capers, dill, lemon juice, and black pepper.",
    ],
    "Pat the cucumber dry so the toast stays crisp.",
  ),
  recipe(
    "sweet-potato-breakfast-hash",
    "Sweet Potato Breakfast Hash",
    35,
    4,
    ["breakfast", "lunch"],
    ["one-pan", "gluten-free"],
    [
      "600 g sweet potato, diced",
      "1 red pepper, diced",
      "1 red onion, diced",
      "2 tbsp olive oil",
      "1 tsp smoked paprika",
      "150 g baby spinach",
      "4 eggs",
      "1 avocado",
      "Salt and black pepper",
    ],
    [
      "Heat the oven to 220°C.",
      "Toss sweet potato, pepper, and onion with oil, paprika, salt, and pepper on a sheet pan.",
      "Roast for 20 minutes, turn, then fold in spinach and make four wells.",
      "Crack in the eggs and bake for 7–9 minutes; serve with avocado.",
    ],
    "Cut the sweet potato into small even cubes so it cooks before the eggs go in.",
  ),
  recipe(
    "chicken-pesto-grain-bowl",
    "Chicken Pesto Grain Bowl",
    35,
    4,
    ["lunch", "dinner"],
    ["high-protein", "mediterranean-inspired"],
    [
      "250 g pearl barley",
      "500 g chicken breast",
      "1 tbsp olive oil",
      "200 g cherry tomatoes",
      "200 g green beans",
      "4 tbsp basil pesto",
      "2 tbsp lemon juice",
      "60 g rocket",
      "Salt and black pepper",
    ],
    [
      "Cook the barley in salted water until tender, then drain.",
      "Season the chicken and cook in olive oil for 6–8 minutes per side until the centre reaches 74°C; rest and slice.",
      "Blanch the green beans and halve the tomatoes.",
      "Toss barley with pesto and lemon, then divide into bowls with chicken, vegetables, and rocket.",
    ],
    "Loosen thick pesto with a spoonful of the warm barley water.",
  ),
  recipe(
    "vietnamese-tofu-noodle-salad",
    "Vietnamese Tofu Noodle Salad",
    30,
    4,
    ["lunch", "dinner"],
    ["vietnamese-inspired", "vegan"],
    [
      "250 g rice noodles",
      "400 g firm tofu, pressed and cubed",
      "1 tbsp neutral oil",
      "1 cucumber, sliced",
      "2 carrots, shredded",
      "1 cup mint and coriander leaves",
      "¼ cup roasted peanuts",
      "2 limes",
      "2 tbsp soy sauce",
      "1 tbsp brown sugar",
      "1 small red chilli, sliced",
    ],
    [
      "Cook the noodles according to the packet, rinse cold, and drain thoroughly.",
      "Fry the tofu in oil for 8–10 minutes, turning until crisp and golden.",
      "Whisk lime juice, soy sauce, sugar, chilli, and 2 tbsp water into a dressing.",
      "Toss noodles with vegetables, herbs, dressing, and tofu; top with peanuts.",
    ],
    "Dress the noodles just before serving so the herbs remain bright.",
  ),
  recipe(
    "greek-chicken-pita",
    "Greek Chicken Pita",
    30,
    4,
    ["lunch", "dinner"],
    ["greek-inspired", "high-protein"],
    [
      "500 g chicken breast, sliced",
      "1 tbsp olive oil",
      "1 tsp dried oregano",
      "1 lemon",
      "4 pita breads",
      "1 cucumber, diced",
      "2 tomatoes, diced",
      "½ red onion, sliced",
      "1 cup shredded lettuce",
      "150 g tzatziki",
    ],
    [
      "Toss chicken with oil, oregano, half the lemon juice, salt, and pepper.",
      "Cook in a hot pan for 6–8 minutes until browned and the centre reaches 74°C.",
      "Warm the pitas and toss cucumber, tomato, and onion with the remaining lemon juice.",
      "Fill each pita with lettuce, chicken, salad, and tzatziki.",
    ],
    "Rest the chicken for 3 minutes before filling the pitas so it stays juicy.",
  ),
  recipe(
    "broccoli-cheddar-soup",
    "Broccoli Cheddar Soup",
    35,
    4,
    ["lunch", "dinner"],
    ["vegetarian", "comfort-food"],
    [
      "2 tbsp butter",
      "1 onion, diced",
      "2 garlic cloves, minced",
      "500 g broccoli, small florets",
      "1 medium potato, diced",
      "750 ml vegetable stock",
      "250 ml milk",
      "180 g mature cheddar, grated",
      "Black pepper",
    ],
    [
      "Soften onion in butter for 7 minutes; add garlic for 1 minute.",
      "Add broccoli stems, potato, and stock and simmer for 12 minutes.",
      "Add broccoli florets and cook for 5 minutes, then blend about half the soup.",
      "Stir in milk and cheddar over low heat until smooth; season with pepper.",
    ],
    "Keep the soup below a simmer after adding cheese to prevent splitting.",
  ),
  recipe(
    "falafel-tabbouleh-bowl",
    "Falafel Tabbouleh Bowl",
    35,
    4,
    ["lunch", "dinner"],
    ["middle-eastern", "vegetarian"],
    [
      "12 cooked falafel",
      "1 cup fine bulgur",
      "2 cups chopped parsley",
      "½ cup chopped mint",
      "3 tomatoes, diced",
      "1 cucumber, diced",
      "3 spring onions, sliced",
      "2 lemons",
      "3 tbsp olive oil",
      "200 g hummus",
      "3 tbsp tahini",
    ],
    [
      "Cover the bulgur with boiling water, stand for 12 minutes, then drain and cool.",
      "Mix bulgur with parsley, mint, tomato, cucumber, and spring onion.",
      "Dress with lemon juice, olive oil, salt, and pepper.",
      "Divide with warm falafel and hummus, then drizzle with tahini loosened with water.",
    ],
    "The tabbouleh should be herb-led, so chop the parsley generously.",
  ),
  recipe(
    "kimchi-tuna-rice-bowl",
    "Kimchi Tuna Rice Bowl",
    15,
    2,
    ["lunch"],
    ["korean-inspired", "quick"],
    [
      "2 cups cooked rice",
      "1 can tuna, drained",
      "¾ cup kimchi, chopped",
      "1 tsp sesame oil",
      "½ cucumber, sliced",
      "2 eggs",
      "1 sheet nori, shredded",
      "2 spring onions, sliced",
      "1 tsp sesame seeds",
    ],
    [
      "Warm the rice and divide it between two bowls.",
      "Mix the tuna with kimchi and sesame oil.",
      "Fry the eggs until the whites set.",
      "Top the rice with tuna mixture, cucumber, eggs, nori, spring onion, and sesame.",
    ],
    "A spoonful of kimchi brine makes the tuna mixture especially lively.",
  ),
  recipe(
    "beetroot-goat-cheese-salad",
    "Beetroot and Goat Cheese Salad",
    45,
    4,
    ["lunch"],
    ["vegetarian", "gluten-free"],
    [
      "600 g raw beetroot, cut into wedges",
      "1 tbsp olive oil",
      "120 g rocket",
      "2 oranges, segmented",
      "120 g soft goat cheese",
      "½ cup walnuts, toasted",
      "1 tbsp balsamic vinegar",
      "1 tsp Dijon mustard",
      "2 tbsp extra-virgin olive oil",
    ],
    [
      "Heat the oven to 210°C and roast the beetroot with 1 tbsp oil and salt for 35 minutes.",
      "Whisk balsamic, mustard, and extra-virgin olive oil into a dressing.",
      "Toss the warm beetroot, rocket, and orange with half the dressing.",
      "Top with goat cheese and walnuts and spoon over the remaining dressing.",
    ],
    "Dress the beetroot while warm so it absorbs more flavour.",
  ),
  recipe(
    "miso-salmon-lunch-bowl",
    "Miso Salmon Lunch Bowl",
    30,
    4,
    ["lunch", "dinner"],
    ["japanese-inspired", "high-protein"],
    [
      "4 salmon fillets",
      "2 tbsp white miso",
      "1 tbsp soy sauce",
      "1 tbsp honey",
      "1 tsp rice vinegar",
      "3 cups cooked brown rice",
      "1 cup shelled edamame",
      "1 cucumber, sliced",
      "2 carrots, ribboned",
      "2 spring onions, sliced",
      "1 tsp sesame seeds",
    ],
    [
      "Heat the oven to 210°C and line a tray.",
      "Mix miso, soy, honey, and vinegar and brush over the salmon.",
      "Bake for 10–13 minutes until the salmon flakes and reaches 63°C in the thickest part.",
      "Build bowls with rice, edamame, cucumber, carrot, salmon, spring onion, and sesame.",
    ],
    "Reserve a little clean glaze before brushing raw fish and spoon it over the finished bowls.",
  ),
  recipe(
    "apricot-trail-mix-bars",
    "Apricot Trail Mix Bars",
    35,
    10,
    ["snack"],
    ["make-ahead", "vegetarian"],
    [
      "2 cups rolled oats",
      "½ cup chopped dried apricots",
      "⅓ cup dried cranberries",
      "½ cup chopped almonds",
      "⅓ cup pumpkin seeds",
      "½ tsp cinnamon",
      "⅓ cup honey",
      "⅓ cup peanut butter",
      "1 tsp vanilla",
    ],
    [
      "Heat the oven to 180°C and line a 20 cm square tin.",
      "Mix oats, fruit, nuts, seeds, and cinnamon.",
      "Warm honey and peanut butter until fluid, stir in vanilla, then mix through the dry ingredients.",
      "Press firmly into the tin and bake for 18–22 minutes; cool completely before cutting.",
    ],
    "Compact the mixture firmly with the base of a glass so the bars hold together.",
  ),
  recipe(
    "cottage-cheese-cucumber-toast",
    "Cottage Cheese Cucumber Toast",
    10,
    2,
    ["breakfast", "snack", "lunch"],
    ["quick", "vegetarian", "high-protein"],
    [
      "4 slices seeded rye bread",
      "200 g cottage cheese",
      "½ cucumber, ribboned",
      "4 radishes, thinly sliced",
      "2 tbsp fresh dill",
      "½ lemon",
      "Black pepper",
    ],
    [
      "Toast the rye bread until crisp.",
      "Spread cottage cheese generously over each slice.",
      "Pat the cucumber dry and arrange it with the radish.",
      "Finish with dill, lemon juice, and black pepper.",
    ],
    "Season the cottage cheese itself before adding the vegetables.",
  ),
  recipe(
    "mango-lassi",
    "Mango Lassi",
    5,
    2,
    ["breakfast", "snack"],
    ["indian-inspired", "no-cook", "vegetarian"],
    [
      "1 large ripe mango, peeled and diced",
      "1 cup plain yogurt",
      "½ cup cold milk",
      "1 tbsp lime juice",
      "1 tsp honey, optional",
      "¼ tsp ground cardamom",
      "4 ice cubes",
    ],
    [
      "Add mango, yogurt, milk, lime, honey, cardamom, and ice to a blender.",
      "Blend until completely smooth and frothy.",
      "Taste and adjust sweetness or loosen with a splash of milk.",
      "Pour into two chilled glasses and serve immediately.",
    ],
    "Frozen mango makes an especially cold, thick lassi without extra ice.",
  ),
  recipe(
    "guacamole-baked-corn-chips",
    "Guacamole with Baked Corn Chips",
    25,
    4,
    ["snack"],
    ["mexican-inspired", "vegan", "gluten-free"],
    [
      "6 corn tortillas",
      "1 tbsp olive oil",
      "3 ripe avocados",
      "1 lime",
      "1 small tomato, diced",
      "¼ red onion, finely diced",
      "2 tbsp chopped coriander",
      "½ jalapeño, minced",
      "Salt",
    ],
    [
      "Heat the oven to 190°C. Cut tortillas into wedges, brush with oil, season, and bake for 10–12 minutes until crisp.",
      "Mash the avocados with lime juice and salt, leaving some texture.",
      "Fold in tomato, onion, coriander, and jalapeño.",
      "Serve at once with the warm corn chips.",
    ],
    "Press reusable wrap directly onto leftover guacamole to slow browning.",
  ),
  recipe(
    "tahini-stuffed-dates",
    "Tahini Stuffed Dates",
    15,
    8,
    ["snack"],
    ["no-cook", "vegan"],
    [
      "16 Medjool dates",
      "⅓ cup tahini",
      "¼ cup pistachios, chopped",
      "30 g dark chocolate, melted",
      "Flaky salt",
    ],
    [
      "Split each date lengthways and remove the stone.",
      "Fill each cavity with about 1 tsp tahini.",
      "Drizzle lightly with melted chocolate and scatter with pistachios and a little salt.",
      "Chill for 10 minutes to set the chocolate.",
    ],
    "Stir the tahini well before filling so it is creamy rather than oily.",
  ),
  recipe(
    "chicken-tikka-masala",
    "Chicken Tikka Masala",
    45,
    4,
    ["dinner"],
    ["indian-inspired", "high-protein"],
    [
      "600 g boneless chicken thighs, cubed",
      "½ cup plain yogurt",
      "2 tbsp tikka spice blend",
      "1 tbsp neutral oil",
      "1 onion, diced",
      "3 garlic cloves, minced",
      "1 tbsp grated ginger",
      "400 g tomato passata",
      "150 ml cream",
      "Coriander and cooked basmati rice, to serve",
    ],
    [
      "Coat chicken with yogurt, half the spice blend, and salt; marinate for 15 minutes.",
      "Brown the chicken in oil in batches, then transfer to a plate.",
      "Soften onion, add garlic, ginger, and remaining spices, then stir in passata and simmer for 10 minutes.",
      "Return chicken and simmer until it reaches 74°C; stir in cream and serve with rice and coriander.",
    ],
    "Brown the chicken in batches so the marinade chars instead of steaming.",
  ),
  recipe(
    "roasted-vegetable-lasagne",
    "Roasted Vegetable Lasagne",
    75,
    6,
    ["dinner"],
    ["italian-inspired", "vegetarian", "comfort-food"],
    [
      "2 courgettes, sliced",
      "2 red peppers, chopped",
      "1 red onion, chopped",
      "2 tbsp olive oil",
      "700 g tomato passata",
      "250 g baby spinach",
      "9 lasagne sheets",
      "500 g ricotta",
      "200 g mozzarella, grated",
      "50 g parmesan, grated",
    ],
    [
      "Heat the oven to 220°C and roast courgettes, peppers, and onion with oil for 25 minutes.",
      "Lower the oven to 190°C; stir spinach into the hot vegetables until wilted.",
      "Layer passata, pasta, ricotta, vegetables, and mozzarella in a baking dish, repeating and finishing with cheese.",
      "Cover and bake for 25 minutes, uncover for 15 minutes, then rest for 10 minutes.",
    ],
    "Resting is essential for neat slices and keeps the filling inside the layers.",
  ),
  recipe(
    "teriyaki-salmon-rice-bowl",
    "Teriyaki Salmon Rice Bowl",
    30,
    4,
    ["dinner"],
    ["japanese-inspired", "high-protein"],
    [
      "4 salmon fillets",
      "3 tbsp soy sauce",
      "2 tbsp mirin",
      "1 tbsp honey",
      "1 tsp grated ginger",
      "3 cups cooked rice",
      "300 g broccoli florets",
      "1 cup shelled edamame",
      "2 spring onions, sliced",
      "1 tsp sesame seeds",
    ],
    [
      "Heat the oven to 210°C. Simmer soy, mirin, honey, and ginger for 2 minutes, then cool slightly.",
      "Brush salmon with sauce and bake for 10–13 minutes, brushing again halfway, until it reaches 63°C.",
      "Steam broccoli and edamame until tender-crisp.",
      "Serve salmon over rice with vegetables, spring onion, sesame, and remaining clean sauce.",
    ],
    "Line the tray because the sweet glaze caramelises quickly.",
  ),
  recipe(
    "moroccan-chickpea-tagine",
    "Moroccan Chickpea Tagine",
    45,
    4,
    ["dinner"],
    ["moroccan-inspired", "vegan", "one-pot"],
    [
      "1 tbsp olive oil",
      "1 onion, sliced",
      "2 garlic cloves, minced",
      "1 tsp ground cumin",
      "1 tsp ground coriander",
      "½ tsp cinnamon",
      "600 g sweet potato, cubed",
      "400 g chopped tomatoes",
      "2 cans chickpeas, drained",
      "100 g dried apricots, halved",
      "500 ml vegetable stock",
      "Couscous and coriander, to serve",
    ],
    [
      "Soften onion in oil for 7 minutes, then add garlic and spices for 1 minute.",
      "Add sweet potato, tomatoes, chickpeas, apricots, and stock.",
      "Cover and simmer for 25 minutes, then uncover and cook until the sauce thickens and sweet potato is tender.",
      "Season and serve with couscous and coriander.",
    ],
    "A squeeze of lemon at the table balances the apricots' sweetness.",
  ),
  recipe(
    "ginger-pork-dumpling-bowl",
    "Ginger Pork Dumpling Bowl",
    25,
    4,
    ["dinner"],
    ["asian-inspired", "quick"],
    [
      "20 frozen pork dumplings",
      "1 tbsp neutral oil",
      "250 g pak choi",
      "1 cucumber, ribboned",
      "3 spring onions, sliced",
      "1 tbsp soy sauce",
      "1 tbsp rice vinegar",
      "1 tsp grated ginger",
      "1 tsp sesame oil",
      "1 tsp sesame seeds",
    ],
    [
      "Whisk soy sauce, vinegar, ginger, sesame oil, and 2 tbsp water.",
      "Brown dumplings in neutral oil, add ⅓ cup water, cover, and steam according to the packet until the pork filling is fully cooked.",
      "Remove the lid and let the bases crisp again; sauté the pak choi alongside for 2–3 minutes.",
      "Divide with cucumber and pak choi, then spoon over dressing and add spring onion and sesame.",
    ],
    "Check the dumpling packet for its specific cooking time, especially for raw fillings.",
  ),
  recipe(
    "baked-cod-tomatoes-olives",
    "Baked Cod with Tomatoes and Olives",
    35,
    4,
    ["dinner"],
    ["mediterranean", "one-pan", "high-protein"],
    [
      "4 cod fillets",
      "400 g cherry tomatoes",
      "1 can cannellini beans, drained",
      "100 g mixed olives",
      "2 garlic cloves, sliced",
      "2 tbsp olive oil",
      "1 lemon",
      "2 tbsp chopped parsley",
      "Salt and black pepper",
    ],
    [
      "Heat the oven to 210°C.",
      "Toss tomatoes, beans, olives, and garlic with oil in a baking dish and roast for 12 minutes.",
      "Season the cod, nestle it into the vegetables, and add lemon slices.",
      "Bake for 10–14 minutes until the fish is opaque and reaches 63°C; finish with parsley.",
    ],
    "Choose fillets of similar thickness so they finish together.",
  ),
  recipe(
    "butternut-squash-gnocchi",
    "Butternut Squash Gnocchi",
    35,
    4,
    ["dinner"],
    ["italian-inspired", "vegetarian"],
    [
      "600 g butternut squash, cubed",
      "2 tbsp olive oil",
      "800 g potato gnocchi",
      "60 g butter",
      "12 sage leaves",
      "150 g baby spinach",
      "60 g parmesan, finely grated",
      "Salt and black pepper",
    ],
    [
      "Heat the oven to 220°C and roast squash with olive oil for 22–25 minutes.",
      "Boil the gnocchi until they float, drain, and reserve ½ cup cooking water.",
      "Brown the butter with sage in a wide pan, then add gnocchi and cook until lightly golden.",
      "Fold in squash and spinach, loosen with cooking water, and finish with parmesan.",
    ],
    "Let the butter foam and smell nutty, but remove it from the heat before the milk solids burn.",
  ),
  recipe(
    "korean-beef-rice-bowls",
    "Korean Beef Rice Bowls",
    25,
    4,
    ["dinner"],
    ["korean-inspired", "quick"],
    [
      "500 g lean beef mince",
      "2 tbsp soy sauce",
      "1 tbsp brown sugar",
      "1 tbsp gochujang",
      "2 garlic cloves, minced",
      "1 tsp grated ginger",
      "1 tsp sesame oil",
      "3 cups cooked rice",
      "1 cucumber, sliced",
      "2 carrots, shredded",
      "1 cup kimchi",
      "2 spring onions, sliced",
    ],
    [
      "Whisk soy sauce, sugar, gochujang, garlic, ginger, and sesame oil.",
      "Brown the beef over high heat for 7–9 minutes until fully cooked and no pink remains.",
      "Pour in the sauce and cook for 2 minutes until glossy.",
      "Serve over rice with cucumber, carrot, kimchi, and spring onion.",
    ],
    "Leave the beef undisturbed for short stretches so it develops crisp browned edges.",
  ),
  recipe(
    "thai-green-chicken-curry",
    "Thai Green Chicken Curry",
    35,
    4,
    ["dinner"],
    ["thai-inspired", "one-pot"],
    [
      "1 tbsp neutral oil",
      "3 tbsp Thai green curry paste",
      "600 g chicken breast, sliced",
      "400 ml coconut milk",
      "200 ml chicken stock",
      "1 aubergine, sliced",
      "200 g green beans",
      "1 tsp brown sugar",
      "1 tbsp fish sauce",
      "1 lime",
      "Thai basil and jasmine rice, to serve",
    ],
    [
      "Fry the curry paste in oil for 1 minute until fragrant.",
      "Add chicken and stir for 3 minutes, then pour in coconut milk and stock.",
      "Add aubergine and simmer for 10 minutes; add beans and cook until the chicken reaches 74°C and vegetables are tender.",
      "Season with sugar, fish sauce, and lime, then finish with basil and serve with rice.",
    ],
    "Different curry pastes vary in heat and salt, so season only after simmering.",
  ),
  recipe(
    "black-bean-enchiladas",
    "Black Bean Enchiladas",
    50,
    6,
    ["dinner"],
    ["mexican-inspired", "vegetarian", "comfort-food"],
    [
      "1 tbsp olive oil",
      "1 onion, diced",
      "1 red pepper, diced",
      "2 cans black beans, drained",
      "1 cup sweetcorn",
      "1 tsp ground cumin",
      "1 tsp smoked paprika",
      "8 flour tortillas",
      "500 ml enchilada sauce",
      "200 g cheddar, grated",
      "1 avocado and coriander, to serve",
    ],
    [
      "Heat the oven to 200°C. Soften onion and pepper in oil for 7 minutes.",
      "Stir in beans, corn, cumin, paprika, and ⅓ of the enchilada sauce; mash a few beans.",
      "Divide filling among tortillas, roll, and arrange seam-side down over a little sauce in a baking dish.",
      "Top with remaining sauce and cheese, bake for 20 minutes, and finish with avocado and coriander.",
    ],
    "Warm the tortillas briefly before rolling so they do not crack.",
  ),
];
